
services:
  app:
    image: php:8.1
    build:
      context: ./translationManagement
      dockerfile: ../Dockerfile  
    container_name: laravel_app
    ports:
      - "8000:8000" 
    volumes:
      - ./translationManagement:/var/www/html  
    depends_on:
      - db  

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  
      MYSQL_DATABASE: ${DB_DATABASE}  
      MYSQL_USER: ${DB_USERNAME}  
      MYSQL_PASSWORD: ${DB_PASSWORD}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: translationManagement
      DB_USERNAME: root
      DB_PASSWORD: root 
    volumes:
      - mysql_data:/var/lib/mysql  
    ports:
      - "3306:3306" 
volumes:
  mysql_data:  

